### ISSUE TITLE
请问您是在哪里添加的Rxjava引用

### ISSUE THREAD

**Issue by siokagami** [lidong1665/AndroidRapidLibrary#1]
查看了build.gradle文件，没有发现Rxjava相关的引用，请问您是在哪里添加的？

**Comment by lidong1665** [comment]
在android_library项目的build.gradle中
   compile 'com.squareup.retrofit2:retrofit:2.0.0'
    compile 'com.squareup.retrofit2:converter-gson:2.0.0'
    compile 'com.squareup.retrofit2:adapter-rxjava:2.0.0'
    compile 'io.reactivex:rxjava:1.1.0'
    compile 'io.reactivex:rxandroid:1.1.0'

**Comment by siokagami** [comment]
请问下您的网络请求是怎样放到线程里的？没有看到handler
